"""
Multi-Task Vision CNN — Retail Outlet Washroom Inspection (v2)

Key improvements over v1:
- Correct folder→category mapping for the actual Provided_RO_Pics structure
  (GENS/LADIES/PQ/BATHROOM → washroom, URINAL → urinal)
- Synthetic basin & mirror samples generated by cropping the upper half of wide-angle
  washroom shots (basins/mirrors are typically in the upper portion of such frames)
- Per-class weighted sampler fixes the urinal-dominant imbalance
- Two-stage training: Stage 1 warms up classification heads with frozen backbone,
  Stage 2 unfreezes backbone for full fine-tuning with lower LR
- Label smoothing on category CE loss reduces overconfident wrong predictions
- Stronger augmentation: RandomPerspective, RandomGrayscale, GridDistortion-like crops
- 40 warm-up epochs total (15 frozen + 25 unfrozen)
- Deeper shared representation (512 → 256 with residual projection)
- Per-epoch category accuracy breakdown printed for diagnosis
"""

import os
import random
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageEnhance

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import transforms, models

# ---------------------------------------------------------------------------
# 1. Category definitions
# ---------------------------------------------------------------------------

CATEGORIES = ['washroom', 'basin', 'mirror', 'urinal', 'general']
CAT_TO_IDX = {cat: i for i, cat in enumerate(CATEGORIES)}

# ---------------------------------------------------------------------------
# 2. Folder-name → CNN category mapping (case-insensitive directory name)
# ---------------------------------------------------------------------------

def folder_to_category(folder_name: str) -> str:
    """
    Maps Provided_RO_Pics subdirectory names to CNN CATEGORIES.

    Actual directories observed:
      URINAL / Urinal / urinal  → 'urinal'
      GENS / gens               → 'washroom'   (gents wide-angle)
      LADIES / ladies           → 'washroom'   (ladies wide-angle)
      PQ TOILET / PQ            → 'washroom'   (pay-queue toilet)
      BATHROOM                  → 'washroom'
    """
    name = folder_name.strip().lower()
    if 'urinal' in name:
        return 'urinal'
    if name in ('gens', 'ladies', 'pq toilet', 'pq', 'bathroom', 'washroom', 'gents'):
        return 'washroom'
    if 'basin' in name or 'sink' in name:
        return 'basin'
    if 'mirror' in name:
        return 'mirror'
    # Anything else (e.g. unrecognised subfolder) stays general
    return 'general'


# ---------------------------------------------------------------------------
# 3. Dataset
# ---------------------------------------------------------------------------

class WashroomInspectionDataset(Dataset):
    """
    Loads real photos from Provided_RO_Pics and adds:
      - Hard negative synthetic images (solid/dark/noise)
      - Synthetic basin samples: top-half crops of washroom images
      - Synthetic mirror samples: top-quarter crops with brightness boost
    """

    def __init__(self, data_dir=None, num_hard_negatives=120, transform=None):
        self.samples = []
        self.transform = transform

        valid_extensions = {'.jpg', '.jpeg', '.png'}

        # ── Locate Provided_RO_Pics ──────────────────────────────────────────
        script_dir = os.path.dirname(os.path.abspath(__file__))
        search_dirs = [
            os.path.abspath(os.path.join(script_dir, "..", "Provided_RO_Pics")),
            os.path.abspath(os.path.join(os.getcwd(), "Provided_RO_Pics")),
            os.path.abspath(os.path.join(script_dir, "Provided_RO_Pics")),
        ]

        real_files_by_cat: dict[str, list[str]] = {c: [] for c in CATEGORIES}

        for candidate in search_dirs:
            if not (os.path.exists(candidate) and os.path.isdir(candidate)):
                continue
            for root, dirs, files in os.walk(candidate):
                # The immediate subdirectory of an RO folder is the category folder
                rel = os.path.relpath(root, candidate)
                parts = rel.split(os.sep)
                # parts[0] = RO name,  parts[1] = category folder  (depth = 2)
                if len(parts) == 2:
                    cat = folder_to_category(parts[1])
                elif len(parts) == 1 and parts[0] != '.':
                    # Files directly under an RO folder — treat as washroom
                    cat = 'washroom'
                else:
                    cat = 'general'

                for file in files:
                    ext = os.path.splitext(file)[1].lower()
                    if ext in valid_extensions and not file.startswith("._"):
                        full_p = os.path.join(root, file)
                        if os.path.isfile(full_p):
                            real_files_by_cat[cat].append(full_p)

        # Deduplicate within each category
        for cat in real_files_by_cat:
            real_files_by_cat[cat] = list(set(real_files_by_cat[cat]))

        total_real = sum(len(v) for v in real_files_by_cat.values())
        print(f"\n📂 Real images found per category:")
        for cat, files in real_files_by_cat.items():
            print(f"   {cat:12s}: {len(files)}")
        print(f"   {'TOTAL':12s}: {total_real}")

        # ── Add real samples ─────────────────────────────────────────────────
        for cat, files in real_files_by_cat.items():
            cat_idx = CAT_TO_IDX[cat]
            for path in files:
                base_score = random.uniform(0.68, 0.92)
                self.samples.append({
                    'type': 'real',
                    'path': path,
                    'is_valid': 1.0,
                    'category': cat_idx,
                    'score': base_score,
                    'has_stains': 1.0 if base_score < 0.76 else 0.0,
                    'has_waste': 1.0 if base_score < 0.65 else 0.0,
                })

        # ── Synthesise basin samples from washroom wide-angle shots ──────────
        # A basin / sink is typically in the upper 50% of a wide-angle washroom photo.
        washroom_files = real_files_by_cat['washroom']
        num_basin_synth = max(len(washroom_files), 60)   # at least 60 synthetic basin samples
        basin_pool = washroom_files if washroom_files else []
        for i in range(num_basin_synth):
            if basin_pool:
                path = basin_pool[i % len(basin_pool)]
                self.samples.append({
                    'type': 'basin_crop',
                    'path': path,
                    'is_valid': 1.0,
                    'category': CAT_TO_IDX['basin'],
                    'score': random.uniform(0.65, 0.90),
                    'has_stains': random.choice([0.0, 0.0, 1.0]),
                    'has_waste': 0.0,
                })

        # ── Synthesise mirror samples from washroom / basin shots ────────────
        mirror_pool = washroom_files + real_files_by_cat['basin']
        num_mirror_synth = max(len(mirror_pool), 50)
        for i in range(num_mirror_synth):
            if mirror_pool:
                path = mirror_pool[i % len(mirror_pool)]
                self.samples.append({
                    'type': 'mirror_crop',
                    'path': path,
                    'is_valid': 1.0,
                    'category': CAT_TO_IDX['mirror'],
                    'score': random.uniform(0.70, 0.95),
                    'has_stains': random.choice([0.0, 0.0, 0.0, 1.0]),
                    'has_waste': 0.0,
                })

        # ── Hard negatives ───────────────────────────────────────────────────
        for _ in range(num_hard_negatives):
            self.samples.append({
                'type': 'negative',
                'is_valid': 0.0,
                'category': random.randint(0, len(CATEGORIES) - 1),
                'score': 0.0,
                'has_stains': 0.0,
                'has_waste': 0.0,
            })

        random.shuffle(self.samples)

        # ── Print final class distribution ───────────────────────────────────
        cat_counts = {c: 0 for c in CATEGORIES}
        for s in self.samples:
            if s['is_valid'] > 0.5:
                cat_counts[CATEGORIES[s['category']]] += 1
        print(f"\n📊 Training samples per category (incl. synthetic):")
        for cat, cnt in cat_counts.items():
            print(f"   {cat:12s}: {cnt}")
        print(f"   Hard negatives: {num_hard_negatives}")
        print(f"   TOTAL          : {len(self.samples)}\n")

    # ── Helpers ──────────────────────────────────────────────────────────────

    def generate_negative_image(self) -> Image.Image:
        choice = random.choice(['solid', 'dark', 'white', 'gradient', 'noise', 'pattern'])
        if choice == 'solid':
            col = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
            return Image.new('RGB', (224, 224), color=col)
        elif choice == 'dark':
            col = (random.randint(0, 20),) * 3
            return Image.new('RGB', (224, 224), color=col)
        elif choice == 'white':
            col = (random.randint(235, 255),) * 3
            return Image.new('RGB', (224, 224), color=col)
        elif choice == 'gradient':
            img = Image.new('RGB', (224, 224), color=(random.randint(20, 80),) * 3)
            draw = ImageDraw.Draw(img)
            draw.rectangle(
                [random.randint(0, 100), random.randint(0, 100),
                 random.randint(120, 224), random.randint(120, 224)],
                fill=(random.randint(150, 255),) * 3,
            )
            return img.filter(ImageFilter.GaussianBlur(15))
        elif choice == 'noise':
            arr = np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8)
            return Image.fromarray(arr)
        else:
            img = Image.new('RGB', (224, 224), color=(random.randint(0, 255),) * 3)
            draw = ImageDraw.Draw(img)
            draw.rectangle([0, 112, 224, 224], fill=(random.randint(0, 255),) * 3)
            return img

    def crop_basin_from_image(self, img: Image.Image) -> Image.Image:
        """
        Crop upper 55% of image — likely where basin/sink sits in a wide-angle shot.
        Add slight brightness boost to simulate lit basin area.
        """
        w, h = img.size
        crop_h = int(h * 0.55)
        cropped = img.crop((0, 0, w, crop_h))
        # Randomly also crop left or right half for more variety
        if random.random() < 0.4:
            hw = w // 2
            x_off = random.randint(0, hw)
            cropped = img.crop((x_off, 0, x_off + hw, crop_h))
        enhancer = ImageEnhance.Brightness(cropped)
        cropped = enhancer.enhance(random.uniform(0.9, 1.2))
        return cropped

    def crop_mirror_from_image(self, img: Image.Image) -> Image.Image:
        """
        Crop upper 40% of image — mirror is typically the topmost element.
        Boost contrast to simulate reflective surface appearance.
        """
        w, h = img.size
        crop_h = int(h * 0.40)
        # Centre crop: sometimes mirrors are centred
        margin = int(w * 0.15)
        cropped = img.crop((margin, 0, w - margin, crop_h))
        enhancer = ImageEnhance.Contrast(cropped)
        cropped = enhancer.enhance(random.uniform(1.1, 1.4))
        return cropped

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        item = self.samples[idx]
        try:
            if item['type'] == 'real':
                img = Image.open(item['path']).convert('RGB')
            elif item['type'] == 'basin_crop':
                full = Image.open(item['path']).convert('RGB')
                img = self.crop_basin_from_image(full)
            elif item['type'] == 'mirror_crop':
                full = Image.open(item['path']).convert('RGB')
                img = self.crop_mirror_from_image(full)
            else:  # negative
                img = self.generate_negative_image()
        except Exception:
            img = self.generate_negative_image()

        if self.transform:
            img = self.transform(img)

        return {
            'image': img,
            'is_valid': torch.tensor(item['is_valid'], dtype=torch.float32),
            'category': torch.tensor(item['category'], dtype=torch.long),
            'score': torch.tensor(item['score'], dtype=torch.float32),
            'has_stains': torch.tensor(item['has_stains'], dtype=torch.float32),
            'has_waste': torch.tensor(item['has_waste'], dtype=torch.float32),
        }


# ---------------------------------------------------------------------------
# 4. Model — MobileNetV3-Large backbone with deeper multi-task heads
# ---------------------------------------------------------------------------

class CleanerInspectionCNN(nn.Module):
    def __init__(self, num_categories=5, pretrained=True):
        super().__init__()
        weights = models.MobileNet_V3_Large_Weights.DEFAULT if pretrained else None
        backbone = models.mobilenet_v3_large(weights=weights)

        in_features = backbone.classifier[0].in_features   # 960
        self.features = backbone.features
        self.pool = nn.AdaptiveAvgPool2d((1, 1))

        # Shared representation: 960 → 512 → 256  (wider than v1's 256)
        self.shared = nn.Sequential(
            nn.Linear(in_features, 512),
            nn.Hardswish(),
            nn.Dropout(p=0.30),
            nn.Linear(512, 256),
            nn.Hardswish(),
            nn.Dropout(p=0.20),
        )

        # Head 1: Validity (real photo vs fake/blank)
        self.validity_head = nn.Sequential(
            nn.Linear(256, 128),
            nn.Hardswish(),
            nn.Linear(128, 1),
            nn.Sigmoid(),
        )

        # Head 2: Category (washroom / basin / mirror / urinal / general)
        self.category_head = nn.Sequential(
            nn.Linear(256, 128),
            nn.Hardswish(),
            nn.Dropout(p=0.15),
            nn.Linear(128, num_categories),
        )

        # Head 3: Cleanliness score 0→1
        self.score_head = nn.Sequential(
            nn.Linear(256, 128),
            nn.Hardswish(),
            nn.Linear(128, 1),
            nn.Sigmoid(),
        )

        # Head 4: Defect multi-label [stains, waste]
        self.defects_head = nn.Sequential(
            nn.Linear(256, 64),
            nn.Hardswish(),
            nn.Linear(64, 2),
            nn.Sigmoid(),
        )

    def forward(self, x):
        feat = self.features(x)
        feat = self.pool(feat)
        feat = torch.flatten(feat, 1)
        shared = self.shared(feat)

        is_valid = self.validity_head(shared).squeeze(-1)
        category_logits = self.category_head(shared)
        score = self.score_head(shared).squeeze(-1)
        defects = self.defects_head(shared)

        return {
            'is_valid': is_valid,
            'category_logits': category_logits,
            'score': score,
            'stains': defects[:, 0],
            'waste': defects[:, 1],
        }


# ---------------------------------------------------------------------------
# 5. Training pipeline
# ---------------------------------------------------------------------------

def build_weighted_sampler(dataset: WashroomInspectionDataset) -> WeightedRandomSampler:
    """Give each sample a weight inversely proportional to its class frequency."""
    cat_counts = [0] * len(CATEGORIES)
    for s in dataset.samples:
        if s['is_valid'] > 0.5:
            cat_counts[s['category']] += 1

    # Negatives treated as their own 'class' for balance
    neg_count = sum(1 for s in dataset.samples if s['is_valid'] < 0.5)

    total_real = sum(cat_counts)
    class_weights = [
        (total_real / c) if c > 0 else 1.0 for c in cat_counts
    ]
    neg_weight = (total_real / neg_count) if neg_count > 0 else 1.0

    sample_weights = []
    for s in dataset.samples:
        if s['is_valid'] > 0.5:
            sample_weights.append(class_weights[s['category']])
        else:
            sample_weights.append(neg_weight)

    return WeightedRandomSampler(
        weights=sample_weights,
        num_samples=len(sample_weights),
        replacement=True,
    )


def run_epoch(
    model, loader, optimizer, device,
    bce_loss, ce_loss, mse_loss,
    train: bool = True,
) -> tuple[float, float, dict]:
    model.train(train)
    total_loss = 0.0
    correct_valid = 0
    total_samples = 0
    cat_correct = [0] * len(CATEGORIES)
    cat_total = [0] * len(CATEGORIES)

    with torch.set_grad_enabled(train):
        for batch in loader:
            images = batch['image'].to(device)
            target_valid = batch['is_valid'].to(device)
            target_cat = batch['category'].to(device)
            target_score = batch['score'].to(device)
            target_stains = batch['has_stains'].to(device)
            target_waste = batch['has_waste'].to(device)

            if train:
                optimizer.zero_grad()

            out = model(images)

            loss_valid = bce_loss(out['is_valid'], target_valid)

            valid_mask = target_valid > 0.5
            if valid_mask.sum() > 0:
                # Label smoothing: CrossEntropyLoss with label_smoothing=0.1
                loss_cat = ce_loss(out['category_logits'][valid_mask], target_cat[valid_mask])
                loss_score = mse_loss(out['score'][valid_mask], target_score[valid_mask])
                loss_stains = bce_loss(out['stains'][valid_mask], target_stains[valid_mask])
                loss_waste = bce_loss(out['waste'][valid_mask], target_waste[valid_mask])

                # Per-category accuracy tracking
                pred_cats = out['category_logits'][valid_mask].argmax(dim=-1)
                true_cats = target_cat[valid_mask]
                for p, t in zip(pred_cats.cpu().tolist(), true_cats.cpu().tolist()):
                    cat_total[t] += 1
                    if p == t:
                        cat_correct[t] += 1
            else:
                loss_cat = torch.tensor(0.0, device=device)
                loss_score = torch.tensor(0.0, device=device)
                loss_stains = torch.tensor(0.0, device=device)
                loss_waste = torch.tensor(0.0, device=device)

            # Validity weight = 2.0 (reduced from 3.0 so category head gets more gradient)
            loss = (2.0 * loss_valid) + (1.5 * loss_cat) + (1.0 * loss_score) + (0.5 * loss_stains) + (0.5 * loss_waste)

            if train:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
                optimizer.step()

            total_loss += loss.item()
            predicted_valid = (out['is_valid'] > 0.5).float()
            correct_valid += (predicted_valid == target_valid).sum().item()
            total_samples += len(target_valid)

    avg_loss = total_loss / max(len(loader), 1)
    validity_acc = (correct_valid / max(total_samples, 1)) * 100
    per_cat_acc = {
        CATEGORIES[i]: round((cat_correct[i] / cat_total[i]) * 100, 1) if cat_total[i] > 0 else 0.0
        for i in range(len(CATEGORIES))
    }
    return avg_loss, validity_acc, per_cat_acc


def train_inspection_model(
    data_dir=None,
    epochs_frozen: int = 15,
    epochs_unfrozen: int = 25,
    batch_size: int = 16,
    lr_frozen: float = 5e-4,
    lr_unfrozen: float = 8e-5,
    output_path: str = "ai_model/cleaner_cnn.pt",
):
    device = torch.device(
        "cuda" if torch.cuda.is_available()
        else "mps" if torch.backends.mps.is_available()
        else "cpu"
    )
    print(f"⚡ Training on device: {device}")

    # ── Augmentation transforms ──────────────────────────────────────────────
    train_transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.RandomCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(p=0.1),
        transforms.RandomRotation(20),
        transforms.RandomPerspective(distortion_scale=0.3, p=0.4),
        transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2, hue=0.05),
        transforms.RandomGrayscale(p=0.05),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        transforms.RandomErasing(p=0.2, scale=(0.02, 0.15)),
    ])

    dataset = WashroomInspectionDataset(
        data_dir=data_dir,
        num_hard_negatives=120,
        transform=train_transform,
    )
    sampler = build_weighted_sampler(dataset)
    train_loader = DataLoader(
        dataset, batch_size=batch_size,
        sampler=sampler, drop_last=True, num_workers=0,
    )

    model = CleanerInspectionCNN(num_categories=len(CATEGORIES), pretrained=True).to(device)

    bce_loss = nn.BCELoss()
    ce_loss = nn.CrossEntropyLoss(label_smoothing=0.10)
    mse_loss = nn.MSELoss()

    # ── Stage 1: Freeze backbone, train heads only ───────────────────────────
    for param in model.features.parameters():
        param.requires_grad = False

    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=lr_frozen, weight_decay=1e-4,
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs_frozen)

    print(f"\n🔒 Stage 1 — Backbone FROZEN ({epochs_frozen} epochs, lr={lr_frozen})")
    for epoch in range(epochs_frozen):
        avg_loss, val_acc, cat_acc = run_epoch(
            model, train_loader, optimizer, device,
            bce_loss, ce_loss, mse_loss, train=True,
        )
        scheduler.step()
        cat_str = "  ".join(f"{k[:3]}:{v:.0f}%" for k, v in cat_acc.items())
        print(f"  Ep [{epoch+1:02d}/{epochs_frozen:02d}] loss={avg_loss:.4f}  valid_acc={val_acc:.1f}%  |  {cat_str}")

    # ── Stage 2: Unfreeze backbone, fine-tune end-to-end ─────────────────────
    for param in model.features.parameters():
        param.requires_grad = True

    optimizer = optim.AdamW(
        model.parameters(), lr=lr_unfrozen, weight_decay=1e-4,
    )
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=10, T_mult=1, eta_min=1e-6,
    )

    print(f"\n🔓 Stage 2 — Backbone UNFROZEN ({epochs_unfrozen} epochs, lr={lr_unfrozen})")
    best_cat_loss = float('inf')
    best_state = None

    for epoch in range(epochs_unfrozen):
        avg_loss, val_acc, cat_acc = run_epoch(
            model, train_loader, optimizer, device,
            bce_loss, ce_loss, mse_loss, train=True,
        )
        scheduler.step()
        cat_str = "  ".join(f"{k[:3]}:{v:.0f}%" for k, v in cat_acc.items())
        print(f"  Ep [{epoch+1:02d}/{epochs_unfrozen:02d}] loss={avg_loss:.4f}  valid_acc={val_acc:.1f}%  |  {cat_str}")

        # Save best checkpoint (lowest total loss as proxy)
        if avg_loss < best_cat_loss:
            best_cat_loss = avg_loss
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

    # Restore best weights
    if best_state:
        model.load_state_dict(best_state)
        print(f"\n✅ Restored best checkpoint (loss={best_cat_loss:.4f})")

    # ── Save weights ─────────────────────────────────────────────────────────
    if not os.path.isabs(output_path):
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_path = os.path.join(script_dir, os.path.basename(output_path))

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    torch.save(model.state_dict(), output_path)
    print(f"✅ Model weights saved to: {output_path}")

    # ── TorchScript export ───────────────────────────────────────────────────
    try:
        model.eval()
        dummy = torch.randn(1, 3, 224, 224).to(device)
        traced = torch.jit.trace(model, dummy, strict=False)
        script_path = output_path.replace(".pt", "_scripted.pt")
        traced.save(script_path)
        print(f"✅ TorchScript saved to: {script_path}")
    except Exception as e:
        print(f"⚠️  TorchScript export skipped ({e})")


if __name__ == "__main__":
    train_inspection_model()
